cms/CMSBundle/Entity/Syslog.php
<?php

declare(strict_types=1);

namespace Monolith\CMSBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Smart\CoreBundle\Doctrine\ColumnTrait;

/**
 * @ORM\Entity(repositoryClass="Monolith\CMSBundle\Repository\SyslogRepository")
 * @ORM\Table(name="cms_syslog",
 *      indexes={
 *          @ORM\Index(columns={"created_at"}),
 *          @ORM\Index(columns={"bundle"}),
 *          @ORM\Index(columns={"entity"})
 *      }
 * )
 */
class Syslog
{
    use ColumnTrait\Id;
    use ColumnTrait\CreatedAt;
    use ColumnTrait\User;
    use ColumnTrait\IpAddress;

    /**
     * create, update, delete.
     *
     * @var string
     *
     * @ORM\Column(type="string")
     */
    protected $action;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=100)
     */
    protected $bundle;

    /**
     * @var integer
     *
     * @ORM\Column(type="integer", options={"unsigned"=true})
     */
    protected $entity_id;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=50)
     */
    protected $entity;

    /**
     * @var string|null
     *
     * @ORM\Column(type="string", nullable=true)
     */
    protected $domain;

    /**
     * @var array
     *
     * @ORM\Column(type="array")
     */
    protected $old_value;

    /**
     * @var array
     *
     * @ORM\Column(type="array")
     */
    protected $new_value;

    /**
     * Syslog constructor.
     */
    public function __construct()
    {
        $this->created_at = new \DateTime();
        $this->entity_id  = 0;
    }

    /**
     * @return string
     */
    public function getAction(): string
    {
        return $this->action;
    }

    /**
     * @param string $action
     *
     * @return $this
     */
    public function setAction(string $action): Syslog
    {
        $this->action = $action;

        return $this;
    }

    /**
     * @return string
     */
    public function getEntity(): string
    {
        return $this->entity;
    }

    /**
     * @param string $entity
     *
     * @return $this
     */
    public function setEntity(string $entity): Syslog
    {
        $this->entity = $entity;

        return $this;
    }

    /**
     * @return int
     */
    public function getEntityId(): int
    {
        return $this->entity_id;
    }

    /**
     * @param int $entity_id
     *
     * @return $this
     */
    public function setEntityId(int $entity_id): Syslog
    {
        $this->entity_id = $entity_id;

        return $this;
    }

    /**
     * @return array
     */
    public function getOldValue(): array
    {
        return $this->old_value;
    }

    /**
     * @param array $old_value
     *
     * @return $this
     */
    public function setOldValue(array $old_value): Syslog
    {
        $this->old_value = $old_value;

        return $this;
    }

    /**
     * @return array
     */
    public function getNewValue(): array
    {
        return $this->new_value;
    }

    /**
     * @param array $new_value
     *
     * @return $this
     */
    public function setNewValue(array $new_value): Syslog
    {
        $this->new_value = $new_value;

        return $this;
    }

    /**
     * @return string
     */
    public function getBundle(): string
    {
        return $this->bundle;
    }

    /**
     * @param string $bundle
     *
     * @return $this
     */
    public function setBundle(string $bundle): Syslog
    {
        $this->bundle = $bundle;

        return $this;
    }

    /**
     * @return null|string
     */
    public function getDomain(): ?string
    {
        return $this->domain;
    }

    /**
     * @param null|string $domain
     *
     * @return $this
     */
    public function setDomain(?string $domain): Syslog
    {
        $this->domain = $domain;

        return $this;
    }
}

cms/CMSBundle/Resources/views/Admin/Development/database.html.twig
{% extends '@CMS/admin.html.twig' %}

{% block title %}{{ 'Development'|trans }} / {{ parent() }}{% endblock %}

{% block page_header 'Development'|trans %}
{% block page_description 'Отладка и синхронизация' %}
{% block content_header_wrapper '' %}

{% block content_body %}

    Ссылка на базовый сайт:
    {% if prod_url is not empty %}
        <a href="{{ prod_url }}" target="_blank" title="Перейти на сайт в новой вкладке">{{ prod_url }}</a>
        &nbsp;
        <a href="{{ path('cms_admin.development') }}" class="btn btn-info">Локальный лог изменений</a>
        &nbsp;
        <a href="{{ path('cms_admin.development_db') }}" class="btn btn-info">Синхронизация БД</a>
    {% else %}
        [ прописывается в parameters.yml ]
    {% endif %}

    <h2>Синхронизация БД</h2>

    <a href="?start" class="btn btn-success btn-large">Запустить!</a>

{% endblock %}

cms/CMSBundle/Resources/views/Admin/Development/index.html.twig
{% extends '@CMS/admin.html.twig' %}

{% block title %}{{ 'Development'|trans }} / {{ parent() }}{% endblock %}

{% block page_header 'Development'|trans %}
{% block page_description 'Отладка и синхронизация' %}
{% block content_header_wrapper '' %}

{% block content_body %}

    Ссылка на базовый сайт:
    {% if prod_url is not empty %}
        <a href="{{ prod_url }}" target="_blank" title="Перейти на сайт в новой вкладке">{{ prod_url }}</a>
        &nbsp;
        <a href="{{ path('cms_admin.development_sync') }}" class="btn btn-info">Синхронизация</a>
        &nbsp;
        <a href="{{ path('cms_admin.development_db') }}" class="btn btn-info">Синхронизация БД</a>
    {% else %}
        [ прописывается в parameters.yml ]
    {% endif %}

    <h2>Журнал изменений</h2>

    <table class="table table-bordered table-hover billing-main-table">
        <thead><tr>
            <th>{{ 'Date'|trans }}</th>
            <th>{{ 'Action'|trans }}</th>
            <th>{{ 'Entity'|trans }}</th>
            <th>{{ 'Old values'|trans }}</th>
            <th>{{ 'New values'|trans }}</th>
            <th>{{ 'User'|trans }}</th>
        </tr></thead>
        <tbody>

        {% for syslog in pagerfanta.currentPageResults %}
            <tr>
                <td>{{ syslog.createdAt|date('Y-m-d H:i:s') }}</td>
                <td>{{ syslog.action }}</td>
                <td>{{ syslog.bundle }}:{{ syslog.entity }}
                    {% if syslog.entity == 'Folder' %}
                        <a href="{{ path('cms_admin.structure_folder', {'id': syslog.entityId}) }}"><b>{{ cms_folder(syslog.entityId) }}</b></a> (id: {{ syslog.entityId }})
                    {% else %}
                        <b>{{ syslog.entityId }}</b>
                    {% endif %}
                </td>
                <td>
                    <ul>
                        {% for key, val in syslog.oldValue %}
                            <li>{{ key }}:
                                {% if val is iterable  %}
                                    {{ dump(val) }}
                                {% elseif syslog.entity == 'Folder' and key == 'parent_folder' %}
                                    <b>{{ cms_folder(val) }}</b> (id: {{ val }})
                                {% else %}
                                    {{ val|e }}
                                {% endif %}
                            </li>
                        {% endfor %}
                    </ul>
                </td>
                <td>
                    <ul>
                        {% for key, val in syslog.newValue %}
                            <li>{{ key }}:
                                {% if val is iterable  %}
                                    {{ dump(val) }}
                                {% elseif syslog.entity == 'Folder' and key == 'parent_folder' and val is not empty %}
                                    <b>{{ cms_folder(val) }}</b> (id: {{ val }})
                                {% else %}
                                    {{ val|e }}
                                {% endif %}
                            </li>
                        {% endfor %}
                    </ul>
                </td>
                <td>
                    {% if syslog.user %}
                        <a>{{ syslog.user }}</a> (id: {{ syslog.user.id }})
                    {% else %}
                        n/a
                    {% endif %}
                </td>
            </tr>
        {% endfor %}

        </tbody>
    </table>

    {% if pagerfanta.haveToPaginate %}
        <p> Страница: {{ pagerfanta.currentPage }} Записей на страницу: {{ pagerfanta.maxPerPage }}</p>
        {{ pagerfanta(pagerfanta, 'twitter_bootstrap_translated', {'css_container_class': 'pagination pagination-centered'}) }}
    {% endif %}

{% endblock %}

cms/CMSBundle/Resources/views/Admin/Development/sync.html.twig
{% extends '@CMS/admin.html.twig' %}

{% block title %}{{ 'Development'|trans }} / {{ parent() }}{% endblock %}

{% block page_header 'Development'|trans %}
{% block page_description 'Отладка и синхронизация' %}
{% block content_header_wrapper '' %}

{% block content_body %}

    Ссылка на базовый сайт:
    {% if prod_url is not empty %}
        <a href="{{ prod_url }}" target="_blank" title="Перейти на сайт в новой вкладке">{{ prod_url }}</a>
        &nbsp;
        <a href="{{ path('cms_admin.development') }}" class="btn btn-info">Локальный лог изменений</a>
        &nbsp;
        <a href="{{ path('cms_admin.development_db') }}" class="btn btn-info">Синхронизация БД</a>
    {% else %}
        [ прописывается в parameters.yml ]
    {% endif %}

    <h2>Синхронизация журнала изменений</h2>

    <br>

    {% if status %}
        <a class="btn btn-success btn-large">Синхронизовано!</a>
    {% else %}
        <a class="btn btn-danger btn-large">Не синхронизовано!</a>
    {% endif %}

    <br>
    <br>

    <p>{{ message }}</p>

{% endblock %}