cms/Module/Gallery/Entity/Album.php
<?php

declare(strict_types=1);

namespace Monolith\Module\Gallery\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\PersistentCollection;
use Smart\CoreBundle\Doctrine\ColumnTrait;

/**
 * @ORM\Entity()
 * @ORM\HasLifecycleCallbacks()
 * @ORM\Table(name="gallery_albums")
 */
class Album
{
    use ColumnTrait\Id;
    use ColumnTrait\IsEnabled;
    use ColumnTrait\CreatedAt;
    use ColumnTrait\Description;
    use ColumnTrait\Position;
    use ColumnTrait\Title;
    use ColumnTrait\UpdatedAt;
    use ColumnTrait\User;

    /**
     * @var int
     *
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $cover_image_id;

    /**
     * @var int|null
     *
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $last_image_id;

    /**
     * @var int
     *
     * @ORM\Column(type="integer")
     */
    protected $photos_count;

    /**
     * @var Gallery
     *
     * @ORM\ManyToOne(targetEntity="Gallery", inversedBy="albums")
     */
    protected $gallery;

    /**
     * @var Photo[]|ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="Photo", mappedBy="album")
     */
    protected $photos;

    /**
     * Album constructor.
     */
    public function __construct()
    {
        $this->created_at   = new \DateTime();
        $this->updated_at   = new \DateTime();
        $this->photos_count = 0;
        $this->position     = 0;
    }

    /**
     * @return string
     */
    public function __toString(): string
    {
        return $this->title;
    }

    /**
     * @param int $cover_image_id
     *
     * @return $this
     */
    public function setCoverImageId(?int $cover_image_id): Album
    {
        $this->cover_image_id = $cover_image_id;

        return $this;
    }

    /**
     * @return int
     */
    public function getCoverImageId(): ?int
    {
        return $this->cover_image_id;
    }

    /**
     * @param Gallery $gallery
     *
     * @return $this
     */
    public function setGallery(Gallery $gallery): Album
    {
        $this->gallery = $gallery;

        return $this;
    }

    /**
     * @return Gallery
     */
    public function getGallery(): Gallery
    {
        return $this->gallery;
    }

    /**
     * @param Photo[]|ArrayCollection $photos
     *
     * @return $this
     */
    public function setPhotos($photos): Album
    {
        $this->photos = $photos;

        return $this;
    }

    /**
     * @return Photo[]|ArrayCollection
     */
    public function getPhotos(): PersistentCollection
    {
        return $this->photos;
    }

    /**
     * @param int $photos_count
     *
     * @return $this
     */
    public function setPhotosCount(int $photos_count): Album
    {
        $this->photos_count = $photos_count;

        return $this;
    }

    /**
     * @return int
     */
    public function getPhotosCount(): int
    {
        return $this->photos_count;
    }

    /**
     * @ORM\PreUpdate()
     */
    public function lastUpdatedAt(): void
    {
        $this->updated_at = new \DateTime();
    }

    /**
     * @param int $last_image_id
     *
     * @return $this
     */
    public function setLastImageId(?int $last_image_id): Album
    {
        $this->last_image_id = $last_image_id;

        return $this;
    }

    /**
     * @return int
     */
    public function getLastImageId(): ?int
    {
        return $this->last_image_id;
    }
}

cms/Module/Gallery/Entity/Photo.php
<?php

declare(strict_types=1);

namespace Monolith\Module\Gallery\Entity;

use Doctrine\ORM\Mapping as ORM;
use Smart\CoreBundle\Doctrine\ColumnTrait;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="PhotoRepository")
 * @ORM\Table(name="gallery_photos")
 */
class Photo
{
    use ColumnTrait\Id;
    use ColumnTrait\CreatedAt;
    use ColumnTrait\Description;
    use ColumnTrait\Position;
    use ColumnTrait\User;

    /**
     * @var int
     *
     * @ORM\Column(type="integer")
     */
    protected $image_id;

    /**
     * @var Album
     *
     * @ORM\ManyToOne(targetEntity="Album", inversedBy="photos", fetch="EXTRA_LAZY")
     */
    protected $album;

    /**
     * @var UploadedFile
     *
     * @Assert\File(
     *      maxSize = "10M",
     *      mimeTypes = {"image/jpeg", "image/png", "image/gif"}
     * )
     */
    protected $file;

    /**
     * Photo constructor.
     */
    public function __construct()
    {
        $this->created_at = new \DateTime();
    }

    /**
     * @param Album $album
     *
     * @return $this
     */
    public function setAlbum(Album $album): Photo
    {
        $this->album = $album;

        return $this;
    }

    /**
     * @return Album
     */
    public function getAlbum(): Album
    {
        return $this->album;
    }

    /**
     * @param UploadedFile $file
     *
     * @return $this
     */
    public function setFile(UploadedFile $file): Photo
    {
        $this->file = $file;

        return $this;
    }

    /**
     * @return UploadedFile
     */
    public function getFile(): ?UploadedFile
    {
        return $this->file;
    }

    /**
     * @param int $image_id
     *
     * @return $this
     */
    public function setImageId(int $image_id): Photo
    {
        $this->image_id = $image_id;

        return $this;
    }

    /**
     * @return int
     */
    public function getImageId(): int
    {
        return $this->image_id;
    }
}

cms/Module/Gallery/Resources/views/index.html.twig
<style type="text/css" media="screen">
    .monolith_gallery_album {
        margin: 10px 0 10px 0;
        padding: 0 0 10px 0;
        border-bottom: 1px solid #a6a6a6;
        font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;
    }
    .monolith_gallery_album_title {
        display: block;
        /*color: #2b587a;*/
        font-size: 130%;
        font-weight: bold;
        margin: 5px 0 12px 0;
        text-decoration: none;
    }
    .monolith_gallery_album_title:hover {
        text-decoration: underline;
    }
    .monolith_gallery_album p {
        margin: 10px 0 10px 0;
    }
    .monolith_gallery_album_count_photos,
    .monolith_gallery_album_updated {
        color: #777777;
    }
    .monolith_gallery_album_descr {
        /*color: black;*/
    }
    .monolith_gallery_image {
        position: relative;
        float: left;
        display: table-cell;
        vertical-align: middle;
        margin: 10px;
        width: 200px;
        /*height: 200px;*/
        background-color: #f1f1f1;
        text-align: center;
    }
    .monolith_gallery_table {
        width: 100%;
    }
    .monolith_gallery_table td {
        vertical-align: top;
    }
</style>

{% for album in albums %}
<table class="monolith_gallery_table monolith_gallery_album">
    <tr>
        <td style="width: 200px;">
            <a href="{{ path('monolith_module.gallery.album', {'id': album.id}) }}" class="monolith_gallery_image">
                {{ smart_media_img(album.coverImageId, '200x200') }}
            </a>
        </td>
        <td>
            <a class="monolith_gallery_album_title" href="{{ path('monolith_module.gallery.album', {'id': album.id}) }}">{{ album.title }}</a>
            <p class="monolith_gallery_album_count_photos">{{ album.photosCount }} {{ 'Photos'|trans }}</p>
            <p class="monolith_gallery_album_descr">{{ album.description }}</p>
            {#<p class="monolith_gallery_album_updated">{{ 'Updated'|trans }} {{ album.updatedAt|date('Y-m-d') }}</p>#}
            <p class="monolith_gallery_album_updated">{{ 'Updated'|trans }} {{ album.updatedAt|format_datetime }}</p>
        </td>
    </tr>
</table>
{% endfor %}

cms/Module/Gallery/Resources/views/latest_widget.html.twig
{% include '@GalleryModule/photos.html.twig' %}

cms/Module/Gallery/Resources/views/photos.html.twig
{% set lightbox = felib_use('jquery-colorbox') %}

<style type="text/css" media="screen">
    .monolith_gallery_image {
        position: relative;
        float: left;
        display: table-cell;
        vertical-align: middle;
        margin: 8px;
        width: 200px;
        height: 200px;
        background-color: #f1f1f1;
        text-align: center;
    }
</style>

{% for photo in photos %}
    <a class="monolith_gallery" href="{{ smart_media(photo.imageId) }}" name="image_{{ photo.id }}" title="{{ photo.description }}">
        <div class="monolith_gallery_image" id="monolith_gallery_image_{{ photo.id }}">
            {{ smart_media_img(photo.imageId, '200x200') }}
        </div>
    </a>
{% endfor %}

{% if photos|length == 0 %}
    В альбоме еще нет фотографий
{% else %}
<script>
    $(document).ready(function(){
        $('.monolith_gallery').colorbox({
            rel: 'monolith_gallery',
            scalePhotos: true,
            scrolling: true,
            fadeOut: 100,
            current: "Фото {current} из {total}",
            initialWidth: 200,
            maxHeight: '95%',
            maxWidth: '95%'
        });
    });
</script>
{% endif %}

<div style="clear: both;"></div>