cms/Module/Gallery/Entity/Album.php
<?php

declare(strict_types=1);

namespace Monolith\Module\Gallery\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\PersistentCollection;
use Smart\CoreBundle\Doctrine\ColumnTrait;

/**
 * @ORM\Entity()
 * @ORM\HasLifecycleCallbacks()
 * @ORM\Table(name="gallery_albums")
 */
class Album
{
    use ColumnTrait\Id;
    use ColumnTrait\IsEnabled;
    use ColumnTrait\CreatedAt;
    use ColumnTrait\Description;
    use ColumnTrait\Position;
    use ColumnTrait\Title;
    use ColumnTrait\UpdatedAt;
    use ColumnTrait\User;

    /**
     * @var int
     *
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $cover_image_id;

    /**
     * @var int|null
     *
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $last_image_id;

    /**
     * @var int
     *
     * @ORM\Column(type="integer")
     */
    protected $photos_count;

    /**
     * @var Gallery
     *
     * @ORM\ManyToOne(targetEntity="Gallery", inversedBy="albums")
     */
    protected $gallery;

    /**
     * @var Photo[]|ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="Photo", mappedBy="album")
     */
    protected $photos;

    /**
     * Album constructor.
     */
    public function __construct()
    {
        $this->created_at   = new \DateTime();
        $this->updated_at   = new \DateTime();
        $this->photos_count = 0;
        $this->position     = 0;
    }

    /**
     * @return string
     */
    public function __toString(): string
    {
        return $this->title;
    }

    /**
     * @param int $cover_image_id
     *
     * @return $this
     */
    public function setCoverImageId(?int $cover_image_id): Album
    {
        $this->cover_image_id = $cover_image_id;

        return $this;
    }

    /**
     * @return int
     */
    public function getCoverImageId(): ?int
    {
        return $this->cover_image_id;
    }

    /**
     * @param Gallery $gallery
     *
     * @return $this
     */
    public function setGallery(Gallery $gallery): Album
    {
        $this->gallery = $gallery;

        return $this;
    }

    /**
     * @return Gallery
     */
    public function getGallery(): Gallery
    {
        return $this->gallery;
    }

    /**
     * @param Photo[]|ArrayCollection $photos
     *
     * @return $this
     */
    public function setPhotos($photos): Album
    {
        $this->photos = $photos;

        return $this;
    }

    /**
     * @return Photo[]|ArrayCollection
     */
    public function getPhotos(): PersistentCollection
    {
        return $this->photos;
    }

    /**
     * @param int $photos_count
     *
     * @return $this
     */
    public function setPhotosCount(int $photos_count): Album
    {
        $this->photos_count = $photos_count;

        return $this;
    }

    /**
     * @return int
     */
    public function getPhotosCount(): int
    {
        return $this->photos_count;
    }

    /**
     * @ORM\PreUpdate()
     */
    public function lastUpdatedAt(): void
    {
        $this->updated_at = new \DateTime();
    }

    /**
     * @param int $last_image_id
     *
     * @return $this
     */
    public function setLastImageId(?int $last_image_id): Album
    {
        $this->last_image_id = $last_image_id;

        return $this;
    }

    /**
     * @return int
     */
    public function getLastImageId(): ?int
    {
        return $this->last_image_id;
    }
}

cms/Module/Gallery/Entity/Gallery.php
<?php

declare(strict_types=1);

namespace Monolith\Module\Gallery\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\PersistentCollection;
use Smart\CoreBundle\Doctrine\ColumnTrait;
use SmartCore\Bundle\MediaBundle\Entity\Collection;

/**
 * @ORM\Entity()
 * @ORM\Table(name="galleries")
 */
class Gallery
{
    const ORDER_BY_CREATED       = 0;
    const ORDER_BY_POSITION_ASC  = 1;
    const ORDER_BY_POSITION_DESC = 2;
    const ORDER_BY_LAST_PHOTO    = 3; // @todo

    use ColumnTrait\Id;
    use ColumnTrait\CreatedAt;
    use ColumnTrait\Title;
    use ColumnTrait\User;

    /**
     * @var integer
     *
     * @ORM\Column(type="integer", nullable=false)
     */
    protected $order_albums_by;

    /**
     * @var Album[]|ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="Album", mappedBy="gallery")
     */
    protected $albums;

    /**
     * @var Collection
     *
     * @ORM\ManyToOne(targetEntity="SmartCore\Bundle\MediaBundle\Entity\Collection")
     * @ORM\JoinColumn(nullable=false)
     */
    protected $media_collection;

    /**
     * Gallery constructor.
     */
    public function __construct()
    {
        $this->albums           = new ArrayCollection();
        $this->created_at       = new \DateTime();
        $this->order_albums_by  = self::ORDER_BY_CREATED;
    }

    /**
     * @return string
     */
    public function __toString(): string
    {
        return $this->title;
    }

    /**
     * @param Album[]|ArrayCollection $albums
     *
     * @return $this
     */
    public function setAlbums($albums): Gallery
    {
        $this->albums = $albums;

        return $this;
    }

    /**
     * @return Album[]|ArrayCollection
     */
    public function getAlbums(): PersistentCollection
    {
        return $this->albums;
    }

    /**
     * @param Collection $media_collection
     *
     * @return $this
     */
    public function setMediaCollection(Collection $media_collection): Gallery
    {
        $this->media_collection = $media_collection;

        return $this;
    }

    /**
     * @return Collection
     */
    public function getMediaCollection(): ?Collection
    {
        return $this->media_collection;
    }

    /**
     * @return int
     */
    public function getOrderAlbumsBy(): int
    {
        return $this->order_albums_by;
    }

    /**
     * @param int $order_albums_by
     *
     * @return $this
     */
    public function setOrderAlbumsBy(int $order_albums_by): Gallery
    {
        $this->order_albums_by = $order_albums_by;

        return $this;
    }
}

cms/Module/Gallery/Entity/Photo.php
<?php

declare(strict_types=1);

namespace Monolith\Module\Gallery\Entity;

use Doctrine\ORM\Mapping as ORM;
use Smart\CoreBundle\Doctrine\ColumnTrait;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="PhotoRepository")
 * @ORM\Table(name="gallery_photos")
 */
class Photo
{
    use ColumnTrait\Id;
    use ColumnTrait\CreatedAt;
    use ColumnTrait\Description;
    use ColumnTrait\Position;
    use ColumnTrait\User;

    /**
     * @var int
     *
     * @ORM\Column(type="integer")
     */
    protected $image_id;

    /**
     * @var Album
     *
     * @ORM\ManyToOne(targetEntity="Album", inversedBy="photos", fetch="EXTRA_LAZY")
     */
    protected $album;

    /**
     * @var UploadedFile
     *
     * @Assert\File(
     *      maxSize = "10M",
     *      mimeTypes = {"image/jpeg", "image/png", "image/gif"}
     * )
     */
    protected $file;

    /**
     * Photo constructor.
     */
    public function __construct()
    {
        $this->created_at = new \DateTime();
    }

    /**
     * @param Album $album
     *
     * @return $this
     */
    public function setAlbum(Album $album): Photo
    {
        $this->album = $album;

        return $this;
    }

    /**
     * @return Album
     */
    public function getAlbum(): Album
    {
        return $this->album;
    }

    /**
     * @param UploadedFile $file
     *
     * @return $this
     */
    public function setFile(UploadedFile $file): Photo
    {
        $this->file = $file;

        return $this;
    }

    /**
     * @return UploadedFile
     */
    public function getFile(): ?UploadedFile
    {
        return $this->file;
    }

    /**
     * @param int $image_id
     *
     * @return $this
     */
    public function setImageId(int $image_id): Photo
    {
        $this->image_id = $image_id;

        return $this;
    }

    /**
     * @return int
     */
    public function getImageId(): int
    {
        return $this->image_id;
    }
}

cms/Module/Gallery/Resources/views/Admin/album.html.twig
{% extends '@GalleryModule/Admin/index.html.twig' %}

{% block title %}{{ album.title }} / {{ parent() }}{% endblock %}

{% block content %}

<div class="box box-body">
    <div class="box-header with-border">

    {% if albumPath %}
        <a class="btn btn-default btn-small btn-sm" href="{{ albumPath }}" title="{{ app.request.host ~ albumPath }}" style="float: right; margin-top: 14px;">
            <i class="icon-home"></i><span class="glyphicon glyphicon-home" aria-hidden="true"></span> Перейти на страницу альбома на сайте
        </a>
    {% endif %}

    <h3>{{ 'Photos of album'|trans }} &laquo;{{ album.title }}&raquo;</h3>

    <a href="../"><i class="fa fa-arrow-circle-o-left"></i> Назад в галерею: &laquo;{{ album.gallery }}&raquo;</a>

    <h4>Загрузить фото</h4>

    {{ form(form, {'attr': {'class': 'form-horizontal well'}} ) }}

    </div>
</div>

<div class="box box-body">
    <div class="box-header with-border">

    <h3>Все фотографии</h3>

    <table class="table table-bordered table-hover">
        <thead><tr>
            <th style="width: 1%;">id</th>
            <th style="width: 1%;">{{ 'Photo'|trans }}</th>
            <th>{{ 'Description'|trans }}</th>
            <th style="width: 180px;">{{ 'Created at'|trans }}</th>
        </tr></thead>
        <tbody>
        {% for photo in photos %}
            <tr id="photo_tr_{{ photo.id }}">
                <td>{{ photo.id }}</td>
                <td>

                    <a href="{{ path('monolith_module.gallery.admin_photo', {'id': photo.id, 'aid': photo.album.id, 'gid': photo.album.gallery.id }) }}">
                        {{ smart_media_img(photo.imageId, '200x200') }}
                    </a>
                </td>
                <td>
                    {{ photo.description }}

                    {#
                    <a href="{{ path('monolith_module.gallery.admin_gallery_edit', {'id': album.gallery.id }) }}" style="float: right;" onclick="return confirm('Вы уверены, что хотите удалить фотографию?')">
                        <i class="icon-remove" title="{{ 'Delete'|trans }}"></i>
                    </a>
                    #}
                </td>
                <td>{{ photo.createdAt|format_datetime }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    </div>
</div>

{% endblock content %}

cms/Module/Gallery/Resources/views/Admin/album_edit.html.twig
{% extends '@GalleryModule/Admin/index.html.twig' %}

{% block title %}{{ 'Edit'|trans }}: {{ album.title }} / {{ parent() }}{% endblock %}

{% block content %}

<div class="box box-primary">
    <div class="box-header with-border">

    <a href="{{ path('monolith_module.gallery.admin_gallery', {'id': album.gallery.id }) }}" style="float: right; margin-top: 14px;"> &laquo; Назад в галерею: {{ album.gallery }}</a>

    <h3>{{ 'Edit album'|trans }}: {{ album.title }}</h3>

    {{ form(form, {'attr': {'class': 'form-horizontal well'}} ) }}

    </div>
</div>

{% endblock content %}

cms/Module/Gallery/Resources/views/Admin/gallery.html.twig
{% extends '@GalleryModule/Admin/index.html.twig' %}

{% block title %}{{ gallery.title }} / {{ parent() }}{% endblock %}

{% block content %}
<div class="box ">
    <div class="box-body">

    {% if folderPath %}
        <a class="btn btn-default btn-small btn-sm" href="{{ folderPath }}" title="{{ app.request.host ~ folderPath }}" style="float: right; margin-top: 14px;">
            <i class="icon-home"></i><span class="glyphicon glyphicon-home" aria-hidden="true"></span> Перейти на страницу фотогалереи на сайте
        </a>
    {% endif %}

    <a class="btn btn-small btn-link" href="{{ path('monolith_module.gallery.admin') }}" style="float: right; margin-top: 14px;"> &laquo; Назад к списку галерей</a>

    <h3>{{ 'Albums'|trans }} &laquo;{{ gallery.title }}&raquo;</h3>

    <table class="table table-bordered table-hover">
        <thead><tr>
            <th style="width: 1%;">id</th>
            <th style="width: 200px;">{{ 'Cover'|trans }}</th>
            <th style="width: 20%;">{{ 'Title'|trans }}</th>
            <th>{{ 'Description'|trans }}</th>
            <th style="width: 1%;">{{ 'Photos'|trans }}</th>
            <th style="width: 1%;">{{ 'Status'|trans }}</th>
            <th style="width: 1%;">{{ 'Position'|trans }}</th>
            <th>{{ 'Create datetime'|trans }}</th>
        </tr></thead>
        <tbody>
        {% for album in albums %}
            <tr>
                <td>{{ album.id }}</td>
                <td><a href="{{ path('monolith_module.gallery.admin_album', {'aid': album.id, 'gid': album.gallery.id }) }}">{{ smart_media_img(album.coverImageId, '200x200') }}</a></td>
                <td>
                    <a href="{{ path('monolith_module.gallery.admin_album_edit', {'aid': album.id, 'gid': album.gallery.id }) }}" style="float: right;">
                        <i class="icon-edit" title="{{ 'Edit'|trans }}"></i>
                    </a>

                    <a href="{{ path('monolith_module.gallery.admin_album', {'aid': album.id, 'gid': album.gallery.id }) }}">{{ album.title }}</a>

                    <a href="{{ path('monolith_module.gallery.admin_album_edit', {'aid': album.id, 'gid': album.gallery.id }) }}" style="float: right;">
                        <i class="icon-edit" title="{{ 'Edit'|trans }}"></i><span class="glyphicon glyphicon-edit" aria-hidden="true" title="{{ 'Edit'|trans }}"></span>
                    </a>

                </td>
                <td>{{ album.description }}</td>
                <td>
                    <a href="{{ path('monolith_module.gallery.admin_album', {'aid': album.id, 'gid': album.gallery.id }) }}">
                        {{ album.photos|length }} {# @todo более оптимальный #}
                    </a>
                </td>
                <td>
                    <a href="{{ path('monolith_module.gallery.admin_album_edit', {'aid': album.id, 'gid': album.gallery.id }) }}">
                    {% if album.enabled %}
                        <span class="label label-success">{{ 'Enabled'|trans }}</span>
                    {% else %}
                        <span class="label label-danger label-important">{{ 'Disabled'|trans }}</span>
                    {% endif %}
                    </a>
                </td>
                <td>{{ album.position }}</td>
                <td>{{ album.createdAt|format_datetime }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    </div>
</div>


<h4>Новый альбом</h4>

{% include '@CMS/Form/default.html.twig' %}

{% endblock content %}

cms/Module/Gallery/Resources/views/Admin/gallery_edit.html.twig
{% extends '@GalleryModule/Admin/index.html.twig' %}

{% block title %}{{ 'Edit'|trans }}: {{ gallery.title }} / {{ 'Gallery'|trans }} / {{ parent() }}{% endblock %}

{% block content %}

<div class="box box-primary">
    <div class="box-header with-border">

    <h3>{{ 'Gallery properties'|trans }}: {{ gallery.title }}</h3>

    {{ form(form, {'attr': {'class': 'form-horizontal well'}} ) }}

    </div>
</div>

{% endblock content %}

cms/Module/Gallery/Resources/views/Admin/index.html.twig
{% extends '@CMS/Admin/module.html.twig' %}

{% block title %}{{ 'Galleries'|trans }} / {{ parent() }}{% endblock %}

{% block page_header 'Galleries'|trans %}
{% block page_description 'Module'|trans %}

{% block content %}

<div class="box box-body">
    <div class="box-header with-border">

        <div class="row">
            <div class="col-md-8">
                <h3>{{ 'All'|trans }} {{ 'Galleries'|trans }}</h3>

                <table class="table table-bordered table-hover">
                    <thead><tr>
                        <th style="width: 1%;">id</th>
                        <th>{{ 'Title'|trans }}</th>
                        <th>{{ 'Albums'|trans }}</th>
                        <th>{{ 'Media collection'|trans }}</th>
                        <th>{{ 'Create datetime'|trans }}</th>
                    </tr></thead>
                    <tbody>
                    {% for gallery in galleries %}
                        <tr>
                            <td>{{ gallery.id }}</td>
                            <td><a href="{{ path('monolith_module.gallery.admin_gallery', {'id': gallery.id }) }}">{{ gallery.title }}</a>

                                <a href="{{ path('monolith_module.gallery.admin_gallery_edit', {'id': gallery.id }) }}" style="float: right;">
                                    <i class="icon-edit" title="{{ 'Edit'|trans }}"></i><span class="glyphicon glyphicon-edit" aria-hidden="true" title="{{ 'Edit'|trans }}"></span>
                                </a>
                            </td>
                            <td>{{ gallery.albums|length }}</td>
                            <td>{{ gallery.mediaCollection }}</td>
                            <td>{{ gallery.createdAt|format_datetime }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>

            <div class="col-md-4">
                <h3>Создать галерею</h3>

                {{ form(form, {'attr': {'class': 'form-vertical well'}} ) }}
            </div>

        </div>
    </div>
</div>


{% endblock content %}

cms/Module/Gallery/Resources/views/Admin/photo.html.twig
{% extends '@GalleryModule/Admin/index.html.twig' %}

{% block title %}{{ 'Edit'|trans }}: {{ gallery.title }} / {{ 'Gallery'|trans }} / {{ parent() }}{% endblock %}

{% block content %}

<div class="box box-primary">
    <div class="box-header with-border">

    <h2>{{ 'Photo'|trans }}</h2>

    {{ smart_media_img(photo.imageId, '200x200') }}

    <p>
        <a href="{{ path('monolith_module.gallery.admin_photo_make_cover', {'id': photo.id, 'aid': photo.album.id, 'gid': photo.album.gallery.id}) }}">
            Сделать обложкой альбома
        </a>
    </p>

    {{ form(form, {'attr': {'class': 'form-vertical'}} ) }}

    </div>
</div>

{% endblock content %}